Iaaf.CMSKnowledgeCentre/Controllers/QuestionController.cs
using ITOK.Core.Common;
using ITOK.Core.Data;
using ITOK.Core.Services.CMS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITOK.Core.Data.Model;
using ITOK.Core.Services.Core;

namespace CMS.Controllers
{
    public class QuestionController : Controller
    {
        private readonly IQuestionService _questionService;

        private IMongoRepository1 mongoRepository;


        public QuestionController()
        {
            mongoRepository = AppKernel.GetInstance<IMongoRepository1>();
            _questionService = AppKernel.GetInstance<IQuestionService>();

        }

        public QuestionController(IMongoRepository1 _mongoRepository)
        {
            this.mongoRepository = _mongoRepository;
            _questionService = AppKernel.GetInstance<IQuestionService>();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetQuestionDetail(string ParentTagSlug, string ParentTagId, string questionId = "")
        {
            Question question = new Question();
            if (!string.IsNullOrEmpty(questionId))
            {
                question = _questionService.FindById(questionId);
            }
            else
            {
                question.ParentTagId = ParentTagId;
                question.ParentTagSlug = ParentTagSlug;
            }



            return PartialView(question);
        }

        [HttpPost]
        public ActionResult GetQuestionDetail(Question question)
        {
            _questionService.Save(question);

            List<Question> allQuestions = _questionService.All().Where(i => i.ParentTagId == question.ParentTagId).ToList();

            return PartialView("QuestionList", allQuestions);
        }
        public ActionResult RemoveQuestion(string tagId, string questionid)
        {
            Question qToDelete = _questionService.FindById(questionid);
            _questionService.Delete(questionid);

            List<Question> allQuestions = _questionService.All().Where(i => i.ParentTagId == qToDelete.ParentTagId).ToList();

            return PartialView("QuestionList", allQuestions);
        }


    }
}

Iaaf.CMSKnowledgeCentre/Views/Question/GetQuestionDetail.cshtml
@using ITOK.Core.Common.Constants
@using ITOK.Core.Common.HtmlExtensions
@model ITOK.Core.Data.Model.Question
@{
    ViewBag.Title = "Get Question Detail";
}
<style>
    
</style>

<div>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Add/Edit</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("GetQuestionDetail", "Question", FormMethod.Post, new { @Id = "AddCategoryForm" }))
                {
                    @Html.AntiForgeryToken()
                <ul class="list-unstyled">
                    <li class="form-group">
                        @*maxchars" maxchars="110"*@
                        <label for="title">
                            Question Text<span class="required_star">*</span>
                        </label>
                        @Html.TextBoxFor(x => x.QuestionText, new { @class = "form-control", autofocus =true, @maxlength=110 })
                        <span class="error field-validation-valid" id="required-questionText">Please enter question</span>
                    </li>
                    <li class="form-group">
                        <label for="title">
                            Answer Type<span class="required_star">*</span>
                        </label>
                        @Html.EnumDropDownListFor(m => m.AnswerType, new { @class = "form-control select_answer-type" })

                        @*@Html.DropDownListFor(x => x.AnswerType, new List<SelectListItem>{
               new SelectListItem { Value = "0" , Text = "Numeric"  },
               new SelectListItem { Value = "1" , Text = "Text" },
               new SelectListItem { Value = "3" , Text = "Options"},
               new SelectListItem { Value = "4" , Text = "Attachment"},
               new SelectListItem { Value = "5" , Text = "Template"}
            }, new { @class = "form-control", autofocus = string.Empty })*@
                    </li>

                    <li class="form-group answer-type-input options-type">
                        <label for="title">
                            Options Type
                        </label>
                        @foreach (QuestionOptionType val in Enum.GetValues(typeof(QuestionOptionType)))
                        {
                           
                                @Html.RadioButtonFor(m => m.OptionType, val)<span> @val.ToString() </span>
                           
                        }
                        <span class="error field-validation-valid" id="required-optionType">Please choose a option</span>
                    </li>
                    <li class="form-group answer-type-input options-type">
                        <label for="title">
                            Options<span class="required_star">*</span>
                        </label>
                        @Html.TextBoxFor(x => x.Options, new { id = "text-option", @class = "form-control" })
                        <span class="error field-validation-valid" id="required-optionTypeText">Please enter options</span>
                        @if (Model.AnswerType != AnswerType.Options)
                        {
                            <script>
                                $('.options-type').hide();
                            </script>
                        }
                    </li>
                    <li class="form-group answer-type-input template-type">
                        <label for="title">
                            Select Template<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.QuestionTemplates)
                        </label>
                        @Html.EnumDropDownListFor(x => x.QuestionTemplates, "Please select a template.", new { @class = "form-control", autofocus = string.Empty })
                  
                        <span class="error field-validation-valid" id="required-templateName">Please select template</span>

                        @if (Model.AnswerType != AnswerType.Template)
                        {
                            <script>
                                $('.template-type').hide();
                            </script>
                        }
                    </li>
                    <li class="form-group answer-type-input isattachment-type">
                        <label for="title">
                            Attachment can be uploaded?<span class="required_star">*</span>
                        </label>
                        @Html.CheckBoxFor(x => x.IsAttachment, new { @class = "form-control" })
                        @if (Model.AnswerType != AnswerType.Attachment)
                        {
                            <script>
                                $('.isattachment-type').hide();
                            </script>
                        }
                        else
                        {
                    <script>
                        $("#IsAttachment").prop("checked", true);
                    </script>
                        }
                    </li>

                    <li class="form-group">
                        <label for="title">
                            Order<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Order)
                        </label>
                        @Html.TextBoxFor(x => x.Order, new { @class = "form-control", autofocus = string.Empty })
                        <span class="error field-validation-valid" id="required-order">Please add order number</span>
                    </li>
                </ul>

                    <input type="hidden" name="Id" value="@Model.Id" />
                    <input type="hidden" name="ParentTagSlug" value="@Model.ParentTagSlug" />
                    <input type="hidden" name="ParentTagId" value="@Model.ParentTagId" />
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <input type="button" id="btnSubmitNewQuestion" class="btn btn-primary" value="Submit" onclick="return submitQuestion();" />
            </div>
        </div>
    </div>
</div>

<script src="@Url.CdnContent("~/Scripts/AnswareType.js")" type="text/javascript"></script>

Iaaf.CMSKnowledgeCentre/Views/Question/QuestionList.cshtml
@model List<ITOK.Core.Data.Model.Question>
@{
    ViewBag.Title = "QuestionList";
}

@if (Model.Any())
{
    foreach (var question in Model)
    {

        <div class="col-md-12 question-row">
            @question.QuestionText

            <div class="action-btns pull-right">
                <a class="btn btn-default" href="javascript:editQuestion('@question.Id.ToString()')" title="Edit">
                    <i class="fa fa-pencil" title="Edit"></i>
                </a>
                <a class="btn btn-danger" href="javascript:RemoveQuestion('@question.Id.ToString()')" title="Delete">
                    <i class="fa fa-trash" title="Delete"></i>
                </a>
            </div>
        </div>
    }
}
else
{
    <p>No questions added yet</p>
}